### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by paldepind** [seladb/github-traffic-stats#1]
Hello @seladb. This project looks very useful :+1:  I have two questions:

* What do I do if a want to pull stats from a repository under an organization? I can't use the format from the readme `python github_traffic_stats.py collect -r [github-repo] -u [github-user] -p [github-password]`. I'd need to input both my username and the organization name?
* What about taking a GitHub API token instead of a plain password? I'm not comfortable typing my password on the command line like that.

**Comment by seladb** [comment]
Thanks for making these suggestions!
I'll add support for both shortly

**Comment by paldepind** [comment]
That sounds wonderful! I've been looking around for a way to save GitHub traffic stats and yours looks really nice.

**Comment by seladb** [comment]
Done! please let me know if that's what you meant

**Comment by paldepind** [comment]
Fantastic! It works wonderfully. Thanks a lot.

**Comment by seladb** [comment]
BTW, I just added pip install so it's easier to install it. You can view installation instructions in README.md

**Comment by paldepind** [comment]
I did follow the instructions :smile: You might want to mention that the script uses Python 2. On some Linux distributions one has to use `python2` and `pip2` for Python 2 programs.

**Comment by seladb** [comment]
You're right, I'll do that, thanks!
