### ISSUE TITLE
github_traffic_stats.py collect fails 

### ISSUE THREAD

**Issue by rogerjdeangelis** [seladb/github-traffic-stats#2]
Good Morning

Great python code, I have been using it for over a year, but now I can't get it to work.

Thanks in advance

Microsoft Windows [Version 6.1.7601]                                                 
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.                      
                                                                                     
C:\Windows\system32>cd d:/csv                                                        
                                                                                     
C:\Windows\system32>d:                                                               
                                                                                     
d:\csv>c:/python27/python.exe github_traffic_stats.py collect -r voodoo -u roger     
jdeangelis -p xxxxxxxxxxxxxxx                                                       
Traceback (most recent call last):                                                   
  File "github_traffic_stats.py", line 100, in <module>                              
    main()                                                                           
  File "github_traffic_stats.py", line 97, in main                                   
    collect(db=db, user=args.github_user, passwd=args.github_password, token=arg     
s.github_access_token, repo=args.github_repo, org=args.github_org)                   
  File "github_traffic_stats.py", line 16, in collect                                
    gh = github.GitHub(username=user, password=passwd, access_token=token)           
AttributeError: 'module' object has no attribute 'GitHub'                            
                                                                                     
d:\csv>                                                                              
                
                                                                     

1.

**Comment by seladb** [comment]
did it suddenly start or did you make any change/update to your Python installation?

**Comment by rogerjdeangelis** [comment]
No change

I have over 1,000 repositories that I own. No links to other repos.

I used to be able to produce reports like this( with one line for each of
my 1000+ repos)

As a side note Josh Mulligand github 'traffic' also fails, after 4 repos

REPO
REPOVIEW    REPOUSERS

 Total
 503          236

 utl-clinical-trials-futility-analysis
  43           19
 utl-shift-array-left-eliminating-missings
  38            4
 utl-excel-report-with-two-side-by-side-graphs-below_python
  32           18
 utl-safe-way-import-excel-time-value
  23           10
 utl-partitioning-your-table-for-a-big-parallel-systask-sort
  23            3
 utl-reducing-the-number-of-points-in-a-trajectory
  20            8
 utl-computing-comorbidity-indexes-using-r-and-sas-charlson
  18            9
 utl-identify-subsets-of-compound-keys-that-have-duplicates
  16            2
 utl-rearrange-the-elements-of-a-datastep-array-in-descending-order
  15            1
 utl_percentile_winsorizization_using_r_and_sas_or_wps
   9            1

**Comment by seladb** [comment]
it seems like something is wrong with the `githubpy` module that you have. What I'd suggest is to try one of these 2 options:

- Reinstall it from [PyPi](https://pypi.org/project/github-traffic-stats2/) by running `pip install github-traffic-stats2 `  and run it again with the same params
- Reinstall using Virtualenv, you can see instructions for Linux and MacOS here: https://github.com/seladb/github-traffic-stats#installation-with-virtualenv-linuxmac. For Windows the it is almost similar, let me know if you need more details on how to do it

**Comment by rogerjdeangelis** [comment]
Thanks
 Will rerun

**Comment by rogerjdeangelis** [comment]
Good Morning

Thanks for your quick response

c:\Python27\Scripts>pip install github-traffic-stats2

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date.
A fut
ure version of pip will drop support for Python 2.7.

Requirement already satisfied: github-traffic-stats2 in
c:\python27\lib\site-pac
kages (18.3.1)

Requirement already satisfied: githubpy in c:\python27\lib\site-packages
(from g
ithub-traffic-stats2) (1.1.0)

Requirement already satisfied: pickledb in c:\python27\lib\site-packages
(from g
ithub-traffic-stats2) (0.8.1)

Requirement already satisfied: simplejson in c:\python27\lib\site-packages
(from
 github-traffic-stats2) (3.16.0)

You are using pip version 19.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.



c:\Python27\Scripts>pip install virtualenv

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date.
A fut
ure version of pip will drop support for Python 2.7.

Collecting virtualenv

  Downloading
https://files.pythonhosted.org/packages/33/5d/314c760d4204f64e4a96
8275182b7751bd5c3249094757b39ba987dcfb5a/virtualenv-16.4.3-py2.py3-none-any.whl

(2.0MB)

    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 2.0MB 1.7MB/s

Installing collected packages: virtualenv

  The script virtualenv.exe is installed in 'c:\python27\Scripts' which is
not o
n PATH.

  Consider adding this directory to PATH or, if you prefer to suppress this
warn
ing, use --no-warn-script-location.

Successfully installed virtualenv-16.4.3

You are using pip version 19.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.



c:\Python27\Scripts>





Microsoft Windows [Version 6.1.7601]

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.





d:\csv>c:/python27/python.exe github_traffic_stats.py collect -r
rogerjdeangelis
/sasbcat -u rogerjdeangelis -p xxxxxxxxxxxxxxxx

Traceback (most recent call last):

  File "github_traffic_stats.py", line 100, in <module>

    main()

  File "github_traffic_stats.py", line 97, in main

    collect(db=db, user=args.github_user, passwd=args.github_password,
token=arg
s.github_access_token, repo=args.github_repo, org=args.github_org)

  File "github_traffic_stats.py", line 16, in collect

    gh = github.GitHub(username=user, password=passwd, access_token=token)

AttributeError: 'module' object has no attribute 'GitHub'

**Comment by seladb** [comment]
when using virtualenv, it's not enough to just install it, you should also create a virtualenv environment. 

Please follow these links: 

https://www.geeksforgeeks.org/creating-python-virtual-environment-windows-linux/
https://programwithus.com/learn-to-code/Pip-and-virtualenv-on-Windows/

**Comment by rogerjdeangelis** [comment]
I have Ubuntu linux if that helps?

Do I have to install all of python27 in a virtual environment?

I installed at c:/python27/scripts

Microsoft Windows [Version 6.1.7601]

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.



C:\Windows\system32>cd c:/python27/scripts





c:\Python27\Scripts>virtualenv myenv

New python executable in c:\Python27\Scripts\myenv\Scripts\python.exe

Installing setuptools, pip, wheel...

done.



c:\Python27\Scripts> myenv\Scripts\activate



(myenv) c:\Python27\Scripts>c:/python27/python.exe github_traffic_stats.py
colle
ct -r rogerjdeangelis/sasbcat -u rogerjdeangelis -p xxxxxxxxxxxxxxxx

Traceback (most recent call last):

  File "github_traffic_stats.py", line 100, in <module>

    main()

  File "github_traffic_stats.py", line 97, in main

    collect(db=db, user=args.github_user, passwd=args.github_password,
token=arg
s.github_access_token, repo=args.github_repo, org=args.github_org)

  File "github_traffic_stats.py", line 16, in collect

    gh = github.GitHub(username=user, password=passwd, access_token=token)

AttributeError: 'module' object has no attribute 'GitHub'



(myenv) c:\Python27\Scripts>







(myenv) c:\>py c:/python27/scripts/github_traffic_stats.py collect -r
rogerjdean
gelis/voodoo -u rogerjdeangelis -p sas28rlxxlr82sas

Traceback (most recent call last):

  File "c:/python27/scripts/github_traffic_stats.py", line 1, in <module>

    import github

ImportError: No module named github





(myenv) c:\>py

Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64
bit (AM
D64)] on win32

Type "help", "copyright", "credits" or "license" for more information.

>>> import github

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: No module named github

>>>

**Comment by seladb** [comment]
After running `c:\Python27\Scripts> myenv\Scripts\activate` you should install the project dependencies by running `pip install -r requirements.txt`:
```
c:\Python27\Scripts> myenv\Scripts\activate
(myenv) c:\Python27\Scripts>pip install -r requirements.txt
....
(myenv) c:\Python27\Scripts>c:/python27/python.exe github_traffic_stats.py colle ct -r rogerjdeangelis/sasbcat -u rogerjdeangelis -p xxxxxxxxxxxxxxxx
```

Let me know if it works

**Comment by rogerjdeangelis** [comment]
Sorry to take so long

I think github has changed something?

I was not always able to install the exact version in requirements.txt

c:\Python27\Scripts>myenv\Scripts\activate



(myenv) c:\Python27\Scripts>pip install githubpy==1.1.0

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date.
A fut
ure version of pip will drop support for Python 2.7.



Requirement already satisfied: githubpy==1.1.0 in
c:\python27\lib\site-packages


(1.1.0)

You are using pip version 19.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.



(myenv) c:\Python27\Scripts>pip install simplejson

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date.
A fut
ure version of pip will drop support for Python 2.7.



Requirement already satisfied: simplejson in c:\python27\lib\site-packages
(3.13.2)


You are using pip version 19.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.



(myenv) c:\Python27\Scripts>pip install pickleDB

DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Ple
ase upgrade your Python as Python 2.7 won't be maintained after that date.
A fut
ure version of pip will drop support for Python 2.7.



Requirement already satisfied: pickleDB in c:\python27\lib\site-packages
(0.8.1)


You are using pip version 19.0.1, however version 19.0.3 is available.

You should consider upgrading via the 'python -m pip install --upgrade pip'
comm
and.



(myenv) c:\Python27\Scripts>c:/python27/python.exe github_traffic_stats.py
colle
ct -r rogerjdeangelis/sasbcat -u rogerjdeangelis -p sas28rlxxlr82sas

Traceback (most recent call last):

  File "github_traffic_stats.py", line 100, in <module>

    main()

  File "github_traffic_stats.py", line 97, in main

    collect(db=db, user=args.github_user, passwd=args.github_password,
token=arg
s.github_access_token, repo=args.github_repo, org=args.github_org)

  File "github_traffic_stats.py", line 16, in collect

    gh = github.GitHub(username=user, password=passwd, access_token=token)

AttributeError: 'module' object has no attribute 'GitHub'

**Comment by seladb** [comment]
Let me try that myself and get back to you

**Comment by seladb** [comment]
Instead of trying to install the packages one by one, try to create a new virtualenv and install the packages:

Enter the directory where `github-traffic-stats` is:
```
C:\>cd github-traffic-stats

C:\github-traffic-stats>
```

Create a new virtualenv named "venv"
```
C:\github-traffic-stats>mkvirtualenv venv

New python executable in C:\Users\seladb\Envs\venv\Scripts\python.exe
Installing setuptools, pip, wheel...done.

(venv) C:\github-traffic-stats>
```

Install the requirements:
```
(venv) C:\github-traffic-stats>pip install -r requirements.txt
```

If this command throws an error: `Could not install packages due to an EnvironmentError: [Errno 42] Illegal byte sequence`, just run the same with `-q-` flag (I found this workaround [here](https://stackoverflow.com/questions/53985263/how-can-i-fix-pip-install-error-environmenterror-errno-42-illegal-byte-sequ)):

```
(venv) C:\github-traffic-stats>pip install -r requirements.txt -q
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

(venv) C:\github-traffic-stats>
```

Then you should be able to run `github-traffic-stats`:

```
(venv) C:\github-traffic-stats>python github_traffic_stats.py view -r pcapplusplus
2017-06-13T00:00:00Z {"count": 6, "uniques": 2}
2017-06-14T00:00:00Z {"count": 184, "uniques": 36}
2017-06-15T00:00:00Z {"count": 65, "uniques": 22}
2017-06-16T00:00:00Z {"count": 147, "uniques": 26}
2017-06-17T00:00:00Z {"count": 30, "uniques": 9}
2017-06-18T00:00:00Z {"count": 34, "uniques": 15}
2017-06-19T00:00:00Z {"count": 155, "uniques": 30}
...
...
```

**Comment by rogerjdeangelis** [comment]
Thanks for all your help, I can see that you have it working.

I have tried the three other gthub traffic apps and worked with the
developers but could only read 5 repos or no repos.

I have archived you excellent analysis, I am thinking about adding another
windows machine to my network with a clean install of only win 7, python27
and
your requirements.

Python35 is my default and I think some of the scripts are picking up that
version, ie mkvirtualenv. Npt a strong enough python programmer
to edit the scripts?

I have python27, python35, perl, r, R, rust, SAS, SPSS, STATA, all Office
products, several VMs and VPNs.

Just too mudh stuff.

Thanks again
Roger

**Comment by seladb** [comment]
Python 3.5 might indeed be the reason for this error. I actually never tried github-traffic-stats on Python 3, I've only tried it on Python 2.7.

If you want a clean Windows install, you can download a Windows VM from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

Creating the VM is pretty straight forward, here are some instructions: https://www.addictivetips.com/windows-tips/get-a-windows-10-vm-image-for-virtualbox-and-vmware/

Please let me know how it went

**Comment by seladb** [comment]
Has the issue been resolved? can we close it?

**Comment by rogerjdeangelis** [comment]
Good Morning

Go ahead and close

Thanks for all your help

**Comment by seladb** [comment]
@rogerjdeangelis FYI this project now supports python 3
