### ISSUE TITLE
Feature Request get top referral sources for repo included in DB

### ISSUE THREAD

**Issue by NotoriousRebel** [seladb/github-traffic-stats#6]
Would be pretty nice to see where exactly traffic is coming from :) 
This  might[help](https://developer.github.com/v3/repos/traffic/#get-top-referral-sources).

**Comment by seladb** [comment]
Thanks for your suggestion!

How do you suggest we incorporate this data in the DB? Should we add a column for each referrer?

**Comment by NotoriousRebel** [comment]
That sounds like a good way to do it!

**Comment by seladb** [comment]
Actually I'm not sure adding a column for each referrer would be a good idea because that way we have no control on the number of columns and the data each column contains.

I'm not sure I can find a nice and clean way to do it. What do you think?
